name: Deploy  Pages

on:
  # 推送时执行
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 1、检出源码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # 默认只拉取分支最近一次的 commit，设为 0 代表拉取所有分支所有提交
          fetch-depth: 0
      # 2、安装 Node 环境
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Pnpm
        run: npm install pnpm -g
      # 4、安装依赖
      - name: Install
        run: pnpm install
      - name: WebUI
        run: cd packages/eeeyou-web-ui/
      - name: WebDist
        run: pnpm run build
      - name: CdRoot
        run: cd ../../
      # 5、打包
      - name: Build
        run: pnpm run docs:build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/.vitepress/dist'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2